mchtr lab L476: ST7735_Private_Functions
ST7735_Private_Functions
ST7735
Functions
void st7735_Init (void)
Initialize the ST7735 LCD Component.
void st7735_DisplayOn (void)
Enables the Display.
void st7735_DisplayOff (void)
Disables the Display.
void st7735_SetCursor (uint16_t Xpos, uint16_t Ypos)
Sets Cursor position.
void st7735_WritePixel (uint16_t Xpos, uint16_t Ypos, uint16_t RGBCode)
Writes pixel.
void st7735_WriteReg (uint8_t LCDReg, uint8_t LCDRegValue)
Writes to the selected LCD register.
void st7735_SetDisplayWindow (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets a display window.
void st7735_DrawHLine (uint16_t RGBCode, uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws horizontal line.
void st7735_DrawVLine (uint16_t RGBCode, uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws vertical line.
uint16_t st7735_GetLcdPixelWidth (void)
Gets the LCD pixel Width.
uint16_t st7735_GetLcdPixelHeight (void)
Gets the LCD pixel Height.
void st7735_DrawBitmap (uint16_t Xpos, uint16_t Ypos, uint8_t *pbmp)
Displays a bitmap picture loaded in the internal Flash.
Detailed Description
Function Documentation
st7735_DisplayOff()
void st7735_DisplayOff (void)
Disables the Display.
Parameters
None
Return values
None
Definition at line 230 of file st7735.c.
References LCD_Delay(), LCD_IO_WriteMultipleData(), and LCD_IO_WriteReg().
st7735_DisplayOn()
void st7735_DisplayOn (void)
Enables the Display.
Parameters
None
Return values
None
Definition at line 213 of file st7735.c.
References LCD_Delay(), LCD_IO_WriteMultipleData(), and LCD_IO_WriteReg().
st7735_DrawBitmap()
void st7735_DrawBitmap (uint16_t Xpos, uint16_t Ypos, uint8_t * pbmp)
Displays a bitmap picture loaded in the internal Flash.
Parameters
pbmp pointer to the Bmp picture
Return values
None
Definition at line 402 of file st7735.c.
References LCD_IO_WriteMultipleData(), st7735_SetCursor(), and st7735_WriteReg().
st7735_DrawHLine()
void st7735_DrawHLine (uint16_t RGBCode, uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws horizontal line.
Parameters
RGBCode Specifies the RGB color
Xpos specifies the X position.
Ypos specifies the Y position.
Length specifies the line length.
Return values
None
Definition at line 342 of file st7735.c.
References ArrayRGB, LCD_IO_WriteMultipleData(), and st7735_SetCursor().
st7735_DrawVLine()
void st7735_DrawVLine (uint16_t RGBCode, uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws vertical line.
Parameters
RGBCode Specifies the RGB color
Xpos specifies the X position.
Ypos specifies the Y position.
Length specifies the line length.
Return values
None
Definition at line 366 of file st7735.c.
References st7735_WritePixel().
st7735_GetLcdPixelHeight()
uint16_t st7735_GetLcdPixelHeight (void)
Gets the LCD pixel Height.
Parameters
None
Return values
The Lcd Pixel Height
Definition at line 392 of file st7735.c.
st7735_GetLcdPixelWidth()
uint16_t st7735_GetLcdPixelWidth (void)
Gets the LCD pixel Width.
Parameters
None
Return values
The Lcd Pixel Width
Definition at line 382 of file st7735.c.
st7735_Init()
void st7735_Init (void)
Initialize the ST7735 LCD Component.
Parameters
None
Return values
None
Definition at line 98 of file st7735.c.
References LCD_IO_Init(), LCD_IO_WriteMultipleData(), LCD_IO_WriteReg(), and st7735_WriteReg().
st7735_SetCursor()
void st7735_SetCursor (uint16_t Xpos, uint16_t Ypos)
Sets Cursor position.
Parameters
Xpos specifies the X position.
Ypos specifies the Y position.
Return values
None
Definition at line 248 of file st7735.c.
References LCD_IO_WriteMultipleData(), and LCD_IO_WriteReg().
Referenced by st7735_DrawBitmap(), st7735_DrawHLine(), and st7735_WritePixel().
st7735_SetDisplayWindow()
void st7735_SetDisplayWindow (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets a display window.
Parameters
Xpos specifies the X bottom left position.
Ypos specifies the Y bottom left position.
Height display window height.
Width display window width.
Return values
None
Definition at line 309 of file st7735.c.
References LCD_IO_WriteMultipleData(), and LCD_IO_WriteReg().
st7735_WritePixel()
void st7735_WritePixel (uint16_t Xpos, uint16_t Ypos, uint16_t RGBCode)
Writes pixel.
Parameters
Xpos specifies the X position.
Ypos specifies the Y position.
RGBCode the RGB pixel color
Return values
None
Definition at line 271 of file st7735.c.
References LCD_IO_WriteMultipleData(), and st7735_SetCursor().
Referenced by st7735_DrawVLine().
st7735_WriteReg()
void st7735_WriteReg (uint8_t LCDReg, uint8_t LCDRegValue)
Writes to the selected LCD register.
Parameters
LCDReg Address of the selected register.
LCDRegValue value to write to the selected register.
Return values
None
Definition at line 295 of file st7735.c.
References LCD_IO_WriteMultipleData(), and LCD_IO_WriteReg().
Referenced by st7735_DrawBitmap(), and st7735_Init().