mchtr lab L476: STM32_ADAFRUIT_LCD_Private_Functions
STM32_ADAFRUIT_LCD_Private_Functions
LCD_ST7735
Functions
uint8_t BSP_LCD_Init (void)
Initializes the LCD.
uint32_t BSP_LCD_GetXSize (void)
Gets the LCD X size.
uint32_t BSP_LCD_GetYSize (void)
Gets the LCD Y size.
uint16_t BSP_LCD_GetTextColor (void)
Gets the LCD text color.
uint16_t BSP_LCD_GetBackColor (void)
Gets the LCD background color.
void BSP_LCD_SetTextColor (uint16_t Color)
Sets the LCD text color.
void BSP_LCD_SetBackColor (uint16_t Color)
Sets the LCD background color.
void BSP_LCD_SetFont (sFONT *pFonts)
Sets the LCD text font.
sFONT * BSP_LCD_GetFont (void)
Gets the LCD text font.
void BSP_LCD_Clear (uint16_t Color)
Clears the whole LCD.
void BSP_LCD_ClearStringLine (uint16_t Line)
Clears the selected line.
void BSP_LCD_DisplayChar (uint16_t Xpos, uint16_t Ypos, uint8_t Ascii)
Displays one character.
void BSP_LCD_DisplayStringAt (uint16_t Xpos, uint16_t Ypos, uint8_t *Text, Line_ModeTypdef Mode)
Displays characters on the LCD.
void BSP_LCD_DisplayStringAtLine (uint16_t Line, uint8_t *ptr)
Displays a character on the LCD.
void BSP_LCD_DrawPixel (uint16_t Xpos, uint16_t Ypos, uint16_t RGB_Code)
Draws a pixel on LCD.
void BSP_LCD_DrawHLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws an horizontal line.
void BSP_LCD_DrawVLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws a vertical line.
void BSP_LCD_DrawLine (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
Draws an uni-line (between two points).
void BSP_LCD_DrawRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a rectangle.
void BSP_LCD_DrawCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a circle.
void BSP_LCD_DrawPolygon (pPoint Points, uint16_t PointCount)
Draws an poly-line (between many points).
void BSP_LCD_DrawEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws an ellipse on LCD.
void BSP_LCD_DrawBitmap (uint16_t Xpos, uint16_t Ypos, uint8_t *pBmp)
Draws a bitmap picture loaded in the STM32 MCU internal memory.
void BSP_LCD_FillRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a full rectangle.
void BSP_LCD_FillCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a full circle.
void BSP_LCD_FillPolygon (pPoint Points, uint16_t PointCount)
Draws a full poly-line (between many points).
void BSP_LCD_FillEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws a full ellipse.
void BSP_LCD_DisplayOn (void)
Enables the display.
void BSP_LCD_DisplayOff (void)
Disables the display.
static void DrawChar (uint16_t Xpos, uint16_t Ypos, const uint8_t *pChar)
Draws a character on LCD.
static void FillTriangle (uint16_t x1, uint16_t x2, uint16_t x3, uint16_t y1, uint16_t y2, uint16_t y3)
Fills a triangle (between 3 points).
static void SetDisplayWindow (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Sets display window.
Detailed Description
Function Documentation
BSP_LCD_Clear()
void BSP_LCD_Clear (uint16_t Color)
Clears the whole LCD.
Parameters
Color Color of the background
Return values
None
Definition at line 241 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawHLine(), BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), BSP_LCD_SetTextColor(), and DrawProp.
Referenced by BSP_LCD_Init(), and main().
BSP_LCD_ClearStringLine()
void BSP_LCD_ClearStringLine (uint16_t Line)
Clears the selected line.
Parameters
Line Line to be cleared This parameter can be one of the following values:
0..9: if the Current fonts is Font16x24
0..19: if the Current fonts is Font12x12 or Font8x12
0..29: if the Current fonts is Font8x8
Return values
None
Definition at line 264 of file stm32_adafruit_lcd.c.
References BSP_LCD_FillRect(), BSP_LCD_GetXSize(), BSP_LCD_SetTextColor(), and DrawProp.
BSP_LCD_DisplayChar()
void BSP_LCD_DisplayChar (uint16_t Xpos, uint16_t Ypos, uint8_t Ascii)
Displays one character.
Parameters
Xpos Start column address
Ypos Line where to display the character shape.
Ascii Character ascii code This parameter must be a number between Min_Data = 0x20 and Max_Data = 0x7E
Return values
None
Definition at line 284 of file stm32_adafruit_lcd.c.
References DrawChar(), and DrawProp.
Referenced by BSP_LCD_DisplayStringAt().
BSP_LCD_DisplayOff()
void BSP_LCD_DisplayOff (void)
Disables the display.
Parameters
None
Return values
None
Definition at line 852 of file stm32_adafruit_lcd.c.
References lcd_drv.
BSP_LCD_DisplayOn()
void BSP_LCD_DisplayOn (void)
Enables the display.
Parameters
None
Return values
None
Definition at line 842 of file stm32_adafruit_lcd.c.
References lcd_drv.
Referenced by main().
BSP_LCD_DisplayStringAt()
void BSP_LCD_DisplayStringAt (uint16_t Xpos, uint16_t Ypos, uint8_t * Text, Line_ModeTypdef Mode)
Displays characters on the LCD.
Parameters
Xpos X position (in pixel)
Ypos Y position (in pixel)
Text Pointer to string to display on LCD
Mode Display mode This parameter can be one of the following values:
CENTER_MODE
RIGHT_MODE
LEFT_MODE
Return values
None
Definition at line 302 of file stm32_adafruit_lcd.c.
References BSP_LCD_DisplayChar(), BSP_LCD_GetXSize(), and DrawProp.
Referenced by BSP_LCD_DisplayStringAtLine().
BSP_LCD_DisplayStringAtLine()
void BSP_LCD_DisplayStringAtLine (uint16_t Line, uint8_t * ptr)
Displays a character on the LCD.
Parameters
Line Line where to display the character shape This parameter can be one of the following values:
0..19: if the Current fonts is Font8
0..12: if the Current fonts is Font12
0...9: if the Current fonts is Font16
0...7: if the Current fonts is Font20
0...5: if the Current fonts is Font24
ptr Pointer to string to display on LCD
Return values
None
Definition at line 363 of file stm32_adafruit_lcd.c.
References BSP_LCD_DisplayStringAt().
Referenced by main().
BSP_LCD_DrawBitmap()
void BSP_LCD_DrawBitmap (uint16_t Xpos, uint16_t Ypos, uint8_t * pBmp)
Draws a bitmap picture loaded in the STM32 MCU internal memory.
Parameters
Xpos Bmp X position in the LCD
Ypos Bmp Y position in the LCD
pBmp Pointer to Bmp picture address
Return values
None
Definition at line 643 of file stm32_adafruit_lcd.c.
References BSP_LCD_GetXSize(), BSP_LCD_GetYSize(), lcd_drv, NULL, SetDisplayWindow(), and st7735_drv.
Referenced by DrawChar().
BSP_LCD_DrawCircle()
void BSP_LCD_DrawCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a circle.
Parameters
Xpos X position
Ypos Y position
Radius Circle radius
Return values
None
Definition at line 532 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawPixel(), BSP_LCD_SetFont(), and DrawProp.
Referenced by BSP_LCD_FillCircle(), and main().
BSP_LCD_DrawEllipse()
void BSP_LCD_DrawEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws an ellipse on LCD.
Parameters
Xpos X position
Ypos Y position
XRadius Ellipse X radius
YRadius Ellipse Y radius
Return values
None
Definition at line 610 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawPixel(), and DrawProp.
BSP_LCD_DrawHLine()
void BSP_LCD_DrawHLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws an horizontal line.
Parameters
Xpos X position
Ypos Y position
Length Line length
Return values
None
Definition at line 390 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawPixel(), DrawProp, lcd_drv, and NULL.
Referenced by BSP_LCD_Clear(), BSP_LCD_DrawRect(), BSP_LCD_FillCircle(), BSP_LCD_FillEllipse(), and BSP_LCD_FillRect().
BSP_LCD_DrawLine()
void BSP_LCD_DrawLine (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
Draws an uni-line (between two points).
Parameters
x1 Point 1 X position
y1 Point 1 Y position
x2 Point 2 X position
y2 Point 2 Y position
Return values
None
Definition at line 439 of file stm32_adafruit_lcd.c.
References ABS, BSP_LCD_DrawPixel(), and DrawProp.
Referenced by BSP_LCD_DrawPolygon(), and FillTriangle().
BSP_LCD_DrawPixel()
void BSP_LCD_DrawPixel (uint16_t Xpos, uint16_t Ypos, uint16_t RGB_Code)
Draws a pixel on LCD.
Parameters
Xpos X position
Ypos Y position
RGB_Code Pixel color in RGB mode (5-6-5)
Return values
None
Definition at line 375 of file stm32_adafruit_lcd.c.
References lcd_drv, and NULL.
Referenced by BSP_LCD_DrawCircle(), BSP_LCD_DrawEllipse(), BSP_LCD_DrawHLine(), BSP_LCD_DrawLine(), and BSP_LCD_DrawVLine().
BSP_LCD_DrawPolygon()
void BSP_LCD_DrawPolygon (pPoint Points, uint16_t PointCount)
Draws an poly-line (between many points).
Parameters
Points Pointer to the points array
PointCount Number of points
Return values
None
Definition at line 582 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawLine().
BSP_LCD_DrawRect()
void BSP_LCD_DrawRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a rectangle.
Parameters
Xpos X position
Ypos Y position
Width Rectangle width
Height Rectangle height
Return values
None
Definition at line 514 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawHLine(), and BSP_LCD_DrawVLine().
BSP_LCD_DrawVLine()
void BSP_LCD_DrawVLine (uint16_t Xpos, uint16_t Ypos, uint16_t Length)
Draws a vertical line.
Parameters
Xpos X position
Ypos Y position
Length Line length
Return values
None
Definition at line 414 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawPixel(), DrawProp, lcd_drv, and NULL.
Referenced by BSP_LCD_DrawRect().
BSP_LCD_FillCircle()
void BSP_LCD_FillCircle (uint16_t Xpos, uint16_t Ypos, uint16_t Radius)
Draws a full circle.
Parameters
Xpos X position
Ypos Y position
Radius Circle radius
Return values
None
Definition at line 695 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawCircle(), BSP_LCD_DrawHLine(), BSP_LCD_SetTextColor(), and DrawProp.
Referenced by main().
BSP_LCD_FillEllipse()
void BSP_LCD_FillEllipse (int Xpos, int Ypos, int XRadius, int YRadius)
Draws a full ellipse.
Parameters
Xpos X position
Ypos Y position
XRadius Ellipse X radius
YRadius Ellipse Y radius
Return values
None
Definition at line 811 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawHLine().
BSP_LCD_FillPolygon()
void BSP_LCD_FillPolygon (pPoint Points, uint16_t PointCount)
Draws a full poly-line (between many points).
Parameters
Points Pointer to the points array
PointCount Number of points
Return values
None
Definition at line 743 of file stm32_adafruit_lcd.c.
References FillTriangle(), POLY_X, and POLY_Y.
BSP_LCD_FillRect()
void BSP_LCD_FillRect (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
Draws a full rectangle.
Parameters
Xpos X position
Ypos Y position
Width Rectangle width
Height Rectangle height
Return values
None
Definition at line 678 of file stm32_adafruit_lcd.c.
References BSP_LCD_DrawHLine(), BSP_LCD_SetTextColor(), and DrawProp.
Referenced by BSP_LCD_ClearStringLine().
BSP_LCD_GetBackColor()
uint16_t BSP_LCD_GetBackColor (void)
Gets the LCD background color.
Parameters
None
Return values
Used background color
Definition at line 191 of file stm32_adafruit_lcd.c.
References DrawProp.
BSP_LCD_GetFont()
sFONT* BSP_LCD_GetFont (void)
Gets the LCD text font.
Parameters
None
Return values
Used font
Definition at line 231 of file stm32_adafruit_lcd.c.
References DrawProp.
BSP_LCD_GetTextColor()
uint16_t BSP_LCD_GetTextColor (void)
Gets the LCD text color.
Parameters
None
Return values
Used text color.
Definition at line 181 of file stm32_adafruit_lcd.c.
References DrawProp.
BSP_LCD_GetXSize()
uint32_t BSP_LCD_GetXSize (void)
Gets the LCD X size.
Parameters
None
Return values
Used LCD X size
Definition at line 161 of file stm32_adafruit_lcd.c.
References lcd_drv.
Referenced by BSP_LCD_Clear(), BSP_LCD_ClearStringLine(), BSP_LCD_DisplayStringAt(), and BSP_LCD_DrawBitmap().
BSP_LCD_GetYSize()
uint32_t BSP_LCD_GetYSize (void)
Gets the LCD Y size.
Parameters
None
Return values
Used LCD Y size
Definition at line 171 of file stm32_adafruit_lcd.c.
References lcd_drv.
Referenced by BSP_LCD_Clear(), and BSP_LCD_DrawBitmap().
BSP_LCD_Init()
uint8_t BSP_LCD_Init (void)
Initializes the LCD.
Parameters
None
Return values
LCD state
Definition at line 129 of file stm32_adafruit_lcd.c.
References BSP_LCD_Clear(), BSP_LCD_SetFont(), DrawProp, lcd_drv, SetDisplayWindow(), and st7735_drv.
Referenced by main().
BSP_LCD_SetBackColor()
void BSP_LCD_SetBackColor (uint16_t Color)
Sets the LCD background color.
Parameters
Color Background color code RGB(5-6-5)
Return values
None
Definition at line 211 of file stm32_adafruit_lcd.c.
References DrawProp.
BSP_LCD_SetFont()
void BSP_LCD_SetFont (sFONT * pFonts)
Sets the LCD text font.
Parameters
pFonts pointer to the font to be used
Return values
None
Definition at line 221 of file stm32_adafruit_lcd.c.
References DrawProp.
Referenced by BSP_LCD_DrawCircle(), and BSP_LCD_Init().
BSP_LCD_SetTextColor()
void BSP_LCD_SetTextColor (uint16_t Color)
Sets the LCD text color.
Parameters
Color Text color code RGB(5-6-5)
Return values
None
Definition at line 201 of file stm32_adafruit_lcd.c.
References DrawProp.
Referenced by BSP_LCD_Clear(), BSP_LCD_ClearStringLine(), BSP_LCD_FillCircle(), and BSP_LCD_FillRect().
DrawChar()
static void DrawChar (uint16_t Xpos, uint16_t Ypos, const uint8_t * pChar) static
Draws a character on LCD.
Parameters
Xpos Line where to display the character shape
Ypos Start column address
pChar Pointer to the character data
Return values
None
Definition at line 868 of file stm32_adafruit_lcd.c.
References bitmap, BSP_LCD_DrawBitmap(), DrawProp, NULL, and OFFSET_BITMAP.
Referenced by BSP_LCD_DisplayChar().
FillTriangle()
static void FillTriangle (uint16_t x1, uint16_t x2, uint16_t x3, uint16_t y1, uint16_t y2, uint16_t y3) static
Fills a triangle (between 3 points).
Parameters
x1 Point 1 X position
y1 Point 1 Y position
x2 Point 2 X position
y2 Point 2 Y position
x3 Point 3 X position
y3 Point 3 Y position
Return values
None
Definition at line 940 of file stm32_adafruit_lcd.c.
References ABS, and BSP_LCD_DrawLine().
Referenced by BSP_LCD_FillPolygon().
SetDisplayWindow()
static void SetDisplayWindow (uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height) static
Sets display window.
Parameters
Xpos LCD X position
Ypos LCD Y position
Width LCD window width
Height LCD window height
Return values
None
Definition at line 1017 of file stm32_adafruit_lcd.c.
References lcd_drv, and NULL.
Referenced by BSP_LCD_DrawBitmap(), and BSP_LCD_Init().